project_name: aws-mfa-auth
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: aws-mfa-auth
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  -
    name: aws-mfa-auth
    tap:
      owner: shu-bc
      name: aws-mfa-auth
    commit_author:
      name: shu-bc
      email: evansdeby@gmail.com
    homepage: https://github.com/shu-bc/aws-mfa-auth
    install: |
      bin.install "aws-mfa-auth"

