# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsMfaAuth < Formula
  desc ""
  homepage "https://github.com/shu-bc/aws-mfa-auth"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/shu-bc/aws-mfa-auth/releases/download/v0.1.1/aws-mfa-auth_darwin_x86_64.tar.gz"
    sha256 "7ff3f7ea08a82ab05bb4e75b1bd70cab06a021d543426bc04044346840dab102"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/shu-bc/aws-mfa-auth/releases/download/v0.1.1/aws-mfa-auth_linux_x86_64.tar.gz"
    sha256 "6c293bd7e31555ad67248cbe48fa2c32fb53268015cd313e0e53e75477d59581"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/shu-bc/aws-mfa-auth/releases/download/v0.1.1/aws-mfa-auth_linux_arm64.tar.gz"
    sha256 "7457286d429ca4c3cde83c7b2384f9b3eda5a628920ae3fbc34ab769b73a7e6f"
  end

  def install
    bin.install "aws-mfa-auth"
  end
end
